---
name: "test"
webhooks:
  discord: ""
info:
    - step:
          description: ""
          path: ""
          user: ""
          command: ""
steps:
    - step:
          description: ""
          path: ""
          user: ""
          command: ""
